# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    container_name: cuponaticDB
    ports:
      - 6603:3306
    command: ['--default-authentication-plugin=mysql_native_password']
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
