# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    container_name: cuponaticDB
    ports:
      - 6603:3306
    command: ['--default-authentication-plugin=mysql_native_password']
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db

  # server:
  #   build: ./backend
  #   expose:
  #     - 3000
  #   environment:
  #     API_HOST: 'localhost'
  #     APP_SERVER_PORT: 3000:3000
  #   ports:
  #     - 3000
  #   volumes:
  #     - ./backend/dist/
  #   command: npm  run-script build
