FROM node:8.7.0-alpine

RUN mkdir -p /srv/app/cuponatic-server
WORKDIR /srv/app/cuponatic-server

COPY package.json /srv/app/cuponatic-server
COPY package-lock.json /srv/app/cuponatic-server

RUN npm install

USER node

COPY . /srv/app/cuponatic-server/


CMD ["node", "/dist/index.js"]